In [8]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.shape

(569, 31)

In [6]:
#train-test-split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [10]:
#scaling
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [11]:
X_train

array([[-0.42945374, -0.0776895 , -0.39866036, ..., -0.33195773,
        -1.26633085, -0.67009172],
       [ 0.29301751, -0.70748991,  0.32877817, ...,  0.41890193,
        -0.51539736, -0.35158673],
       [-0.68260311,  0.14556064, -0.67505405, ..., -0.5051167 ,
         0.47090334,  0.27949507],
       ...,
       [-0.48634124, -0.20223958, -0.51852707, ..., -0.45642046,
         0.11384967, -0.6717085 ],
       [-0.63424874, -0.16463956, -0.56301369, ...,  0.6049155 ,
         2.96067214,  3.01184755],
       [-0.62002686, -0.47953976, -0.63427465, ..., -0.38020027,
        -1.10781824, -1.29255072]])

In [12]:
y_train

355    B
128    B
531    B
256    M
307    B
      ..
544    B
310    B
107    B
31     M
275    B
Name: diagnosis, Length: 455, dtype: object

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0])

## Numpy Array to Pytorch Tensor

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

## Define the model

In [30]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    return -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()

## important parameters

In [31]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [35]:
model = MySimpleNN(X_train_tensor)
# model.weights, model.bias
# print(model.weights.shape)
# print(model.bias.shape)

#Define loop
for epoch in range(100):
  pass
  #forward pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  #loss cal
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(loss)


  #backward
  loss.backward()

  #update params
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch : {epoch+1}, Loss: {loss.item()}')

Epoch : 1, Loss: 4.103995947908584
Epoch : 2, Loss: 3.9980102214012048
Epoch : 3, Loss: 3.8862400513931648
Epoch : 4, Loss: 3.7670180261336133
Epoch : 5, Loss: 3.642545520382945
Epoch : 6, Loss: 3.515985066610502
Epoch : 7, Loss: 3.3818501295094094
Epoch : 8, Loss: 3.2382517729796536
Epoch : 9, Loss: 3.0946174951510756
Epoch : 10, Loss: 2.950660685459506
Epoch : 11, Loss: 2.8025293202846324
Epoch : 12, Loss: 2.643107520137098
Epoch : 13, Loss: 2.4823648152336517
Epoch : 14, Loss: 2.3164965224987375
Epoch : 15, Loss: 2.1514439682221123
Epoch : 16, Loss: 1.9905239073145473
Epoch : 17, Loss: 1.8348345852875039
Epoch : 18, Loss: 1.6805956333826413
Epoch : 19, Loss: 1.5355007296269765
Epoch : 20, Loss: 1.399849594657046
Epoch : 21, Loss: 1.2785916538630755
Epoch : 22, Loss: 1.173247094499656
Epoch : 23, Loss: 1.0845887895769724
Epoch : 24, Loss: 1.0095907435517326
Epoch : 25, Loss: 0.9499059621570854
Epoch : 26, Loss: 0.9031557461720439
Epoch : 27, Loss: 0.8666643290331548
Epoch : 28, Loss: 0.8379897844097809
Epoch : 29, Loss: 0.815164836934991
Epoch : 30, Loss: 0.7967169906133248
Epoch : 31, Loss: 0.781584692905367
Epoch : 32, Loss: 0.7690105690488935
Epoch : 33, Loss: 0.7584499579900446
Epoch : 34, Loss: 0.7495038007370869
Epoch : 35, Loss: 0.7418725603879054
Epoch : 36, Loss: 0.7353254860024331
Epoch : 37, Loss: 0.7296804241778525
Epoch : 38, Loss: 0.7247906403534798
Epoch : 39, Loss: 0.7205361456096405
Epoch : 40, Loss: 0.7168178333371178
Epoch : 41, Loss: 0.7135533404870772
Epoch : 42, Loss: 0.710673976093528
Epoch : 43, Loss: 0.7081223355219679
Epoch : 44, Loss: 0.7058503833573881
Epoch : 45, Loss: 0.7038178798728063
Epoch : 46, Loss: 0.7019910751652342
Epoch : 47, Loss: 0.7003416206897273
Epoch : 48, Loss: 0.6988456614893613
Epoch : 49, Loss: 0.6974830801023376
Epoch : 50, Loss: 0.6962368680474462
Epoch : 51, Loss: 0.6950926044120502
Epoch : 52, Loss: 0.6940380240323175
Epoch : 53, Loss: 0.693062660320442
Epoch : 54, Loss: 0.6921575500526929
Epoch : 55, Loss: 0.6913149894198812
Epoch : 56, Loss: 0.6905283323756742
Epoch : 57, Loss: 0.6897918238143247
Epoch : 58, Loss: 0.6891004613868226
Epoch : 59, Loss: 0.688449880844867
Epoch : 60, Loss: 0.6878362607083277
Epoch : 61, Loss: 0.6872562428067832
Epoch : 62, Loss: 0.6867068658708821
Epoch : 63, Loss: 0.6861855098644294
Epoch : 64, Loss: 0.6856898491709278
Epoch : 65, Loss: 0.6852178130941773
Epoch : 66, Loss: 0.6847675524147581
Epoch : 67, Loss: 0.684337410974037
Epoch : 68, Loss: 0.6839259014442348
Epoch : 69, Loss: 0.6835316845949408
Epoch : 70, Loss: 0.6831535514898139
Epoch : 71, Loss: 0.6827904081474265
Epoch : 72, Loss: 0.6824412622816721
Epoch : 73, Loss: 0.6821052118034596
Epoch : 74, Loss: 0.6817814348194642
Epoch : 75, Loss: 0.6814691809078282
Epoch : 76, Loss: 0.6811677634868334
Epoch : 77, Loss: 0.6808765531221973
Epoch : 78, Loss: 0.6805949716430474
Epoch : 79, Loss: 0.6803224869567563
Epoch : 80, Loss: 0.6800586084695086
Epoch : 81, Loss: 0.6798028830333324
Epoch : 82, Loss: 0.6795548913518946
Epoch : 83, Loss: 0.6793142447870525
Epoch : 84, Loss: 0.6790805825162859
Epoch : 85, Loss: 0.678853568998017
Epoch : 86, Loss: 0.6786328917076287
Epoch : 87, Loss: 0.6784182591119463
Epoch : 88, Loss: 0.6782093988541537
Epoch : 89, Loss: 0.6780060561247322
Epoch : 90, Loss: 0.6778079921970986
Epoch : 91, Loss: 0.6776149831092886
Epoch : 92, Loss: 0.6774268184753313
Epoch : 93, Loss: 0.6772433004119571
Epoch : 94, Loss: 0.6770642425680047
Epoch : 95, Loss: 0.6768894692453987
Epoch : 96, Loss: 0.676718814601887
Epoch : 97, Loss: 0.6765521219268549
Epoch : 98, Loss: 0.6763892429825599
Epoch : 99, Loss: 0.6762300374039801
Epoch : 100, Loss: 0.6760743721512655

In [37]:
model.weights, model.bias

(tensor([[-0.0951],
         [ 0.1939],
         [-0.2057],
         [-0.0168],
         [ 0.3874],
         [-0.6333],
         [-0.1955],
         [ 0.0118],
         [ 0.2127],
         [-0.0327],
         [-0.2983],
         [-0.1516],
         [-0.0265],
         [ 0.1817],
         [ 0.1600],
         [-0.0036],
         [ 0.1086],
         [-0.1154],
         [ 0.0587],
         [ 0.1329],
         [ 0.2076],
         [-0.0696],
         [ 0.4560],
         [-0.0723],
         [-0.3625],
         [-0.2693],
         [ 0.2060],
         [ 0.3253],
         [-0.0806],
         [ 0.2901]], dtype=torch.float64, requires_grad=True),
 tensor([-0.4446], dtype=torch.float64, requires_grad=True))

## Evaluation

In [39]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred==y_test_tensor).float().mean()

print(f"Accuracy : {accuracy.item()}")
print(y_pred, y_train_tensor)

Accuracy : 0.6181902289390564
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]) tensor([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0])

## Future Improvements:
going forward : weights and bias init -> nn module

builtin loss fucn

No-manual-gradient descent